balazsracz/openmrn_cue

- cs/commandstation/TrainDbCdi.hxx
Adds back the function settings to the stored train DB, as JMRI can now handle nested repeated groups all right.
> Ups the size of the stored train database to 32 trains.

- cs/commandstation/TrainNodeInfoCache.cxxtest
- cs/commandstation/TrainNodeInfoCache.hxx
- cs/commandstation/traindb_test_utils.hxx
This scrolling behavior allows centering around a line instead of marking the top line for a page.
> Adds new scrolling behavior to the TrainNodeCache

- cs/commandstation/TrainDbCdi.hxx
Makes the TrainDB size explicitly configured by every target. This avoids problems when two different compilation units accidentally build with different trainDB sizes, at the expense of a bunch of one-time compilation errors during the transition.
> Explicit trainDB size

- cs/commandstation/TrackPowerBit.cxxtest
- cs/commandstation/TrackPowerBit.hxx
- cs/commandstation/UpdateProcessor.cxxtest
- cs/commandstation/track_test_helper.hxx
Updates TrackPowerBit consumer to disable DCC packet refresh and send ESTOP messages to the track when the estop button is pressed.
> Sends ESTOP messages before track off

- cs/commandstation/ProgrammingTrackCVSpace.hxx
- cs/commandstation/ProgrammingTrackFrontend.hxx
- cs/commandstation/ProgrammingTrackSpaceConfig.hxx
- cs/commandstation/UpdateProcessor.hxx
- Updates the commandstation code for API changes in the update loop
- Adds programming track frontend that drives the backend for user visible operations such as CV writes, reads and bit modify operations in service mode.
- Adds a memory space and its CDI configuration for executing programming commands from JMRI.
> Service mode programming frontend

- cs/commandstation/FindProtocolDefs.cxx
- cs/commandstation/FindProtocolDefs.cxxtest
- cs/commandstation/FindProtocolDefs.hxx
Fixes bugs in the input parsing code that lead to problems allocating locomotives on the command station:
- spaces were not correctly handled
- trailing L and M letters now interpreted as longaddress and marklin locomotive selection.
> Fix marklin allocate

- cs/commandstation/FindProtocolDefs.hxx
- cs/commandstation/FindTrainNode.hxx
- cs/commandstation/ProgrammingTrackCVSpace.hxx
- cs/commandstation/ProgrammingTrackFrontend.hxx
- cs/commandstation/ProgrammingTrackSpaceConfig.hxx
- cs/commandstation/TrainDbCdi.hxx
Adds POM support to the ProgrammingTrack CV space classes:
- implements set_node() in the MemorySpace to allow TrainNodes to accept read and write commands
- separates the frontend call depending on what the last set node ID was.
- adds separate POM_{WRITE|READ}_BYTE command to the PRogrammingTrack Frontend 
- implennets the railcom based POM query and write commands in the Frontend, wihtout involving the actual programmingtrack backend.
Also a feature update in FindTrainNode: allows using RemoteFindTrainNode to be used to search for producer for any event ID.
> Implements POM in the Programmingtrack Frontend and CV space

- cs/commandstation/FindProtocolDefs.cxx
- cs/commandstation/FindProtocolDefs.hxx
- cs/commandstation/FindProtocolServer.cxxtest
- cs/commandstation/FindTrainNode.cxxtest
- cs/commandstation/TrainDbDefs.hxx
- cs/commandstation/TrainNodeInfoCache.cxxtest
- cs/commandstation/cm_test_helper.hxx
Makes the find protocol matching algorithm take into account when a protocol restriction
is applied to the find query.
Normally throttles will not specify a protocol restriction (send DEFAULT / 0),
and that returns all trains. But when the throttle does specify the protocol,
we must make sure to return trains only from that protocol.
Adjusts some of the unittests which have incorrectly specified the query parameters.
> Add support for search by protocol.

- cs/commandstation/AllTrainNodes.cxx
- cs/commandstation/AllTrainNodes.cxxtest
- cs/commandstation/AllTrainNodes.hxx
- cs/commandstation/AllTrainNodesInterface.hxx
- cs/commandstation/FindProtocolServer.cxxtest
- cs/commandstation/FindProtocolServer.hxx
- cs/commandstation/UpdateProcessor.hxx
- cs/commandstation/cm_test_helper.hxx
- Adds AllTrainNodesInterface which abstracts away the functionality for AllTrainNodes with respect to the FindProtocolServer.
- switches the train DB identifiers from int to size_t in the interface
Minor fixes:
- Changes to the test infrastructure: refactores common objects into the _test_helper.hxx file.
- Adds missing include guards to UpdateProcessor.hxx
>  Adds an abstract interface to decouple AllTrainNodes from FindProtocolServer.

- cs/commandstation/AllTrainNodes.cxx
- cs/commandstation/AllTrainNodes.cxxtest
- cs/commandstation/AllTrainNodes.hxx
- cs/commandstation/AllTrainNodesInterface.hxx
- cs/commandstation/FindProtocolServer.cxxtest
- cs/commandstation/FindProtocolServer.hxx
- cs/commandstation/FindTrainNode.cxxtest
- cs/commandstation/FindTrainNode.hxx
- cs/commandstation/cm_test_helper.hxx
- Updates all implementations and most uses.
- Removes the implementation of FindTrainNode to look into the local database.
This class is scheduled to be removed altogether.
> Makes the get_traindb_entry function on AllTrainNodes operate in async.

- cs/targets/railcom/main.cxx
Critical fixes:
- Adds missing component that caused the output ports to never be enabled.
- Changes the port initialization order, because the railcom port must be opened before the DCC port.
- Re-initializes the DCC input pin after opening all devices.
Additional improvements:
- Adds an optional component to print all DCC packets in text to the USB port.
- Adds comment about the railcom debug proxy object.
- Optionalizes the CPU-load  display.
- Adds a LED that shows whether we detect DCC signal.
> Fix railcom board firmware.

- cs/commandstation/FindProtocolDefs.cxx
- cs/commandstation/FindProtocolDefs.cxxtest
Takes into account when doing address matches the information and constraints we know about the address type.
Specifically, when the input comes with a long address requested, we will not match a short address DCC train.
> Makes a long address query not match a short address train

- cs/commandstation/ProgrammingTrackFrontend.hxx
We should keep waiting for another repeat of the same programming packet.
> Fix POM reads that return only ACKs in a cutout.

- cs/commandstation/ProgrammingTrackCVSpace.hxx
- cs/commandstation/ProgrammingTrackFrontend.hxx
Adds an encoding for the program track CV space representation that allows expressing a single-bit write.
Implements this in the programming track CV space. Adds API for POM bit operations to the program track frontend, but this is not implemented.
Currently bit operations will only work on the program track. Reads are not supported, just writes.
> Adds support for bit operations in the program track API

- cs/commandstation/ProgrammingTrackFrontend.hxx
- Eliminates the early exit when there is no channel2 feedback. Uses repetitions instead.
- Adds explicit error code when we only see garbage / busy answers from the decoder
(previously this was sending ERROR_FAILED_VERIFY).
> Updates the control flow when interpreting railcom feedback for POM.

- cs/commandstation/ProgrammingTrackFrontend.hxx
This makes us compliant to RCN-216 with a bit of spare.
> Up the initial reset packet count when entering service mode.

- cs/commandstation/FindTrainNode.hxx
Previous deadline was 0.8 seconds and caused unnecessary error code 1030.
> Up the deadline to 3 seconds for train search and allocate.

- cs/commandstation/RailcomBroadcastFlow.hxx
This moves the broadcast event IDs into the standard range (according to new draft as of 2023-03).
> Updates the computation of the railcom broadcast event ID ranges.

- cs/targets/railcom/config.hxx
- cs/targets/railcom/main.cxx
This will ensure that all development parameters are correctly initialized. Adds string defaults as well.
Changes the segment layout to have the port config in the top of the CDI, and the dev options near the bottom.
> Adds factory reset code to the railcom board.

- cs/commandstation/ProgrammingTrackCVSpace.hxx
- cs/commandstation/ProgrammingTrackFrontend.hxx
- cs/commandstation/ProgrammingTrackSpaceConfig.hxx
Adds a new mode "POM with address" to the CV space. (Mode = top 8 bits of the memconfig address.)
When using POM with address, there will be 10-bit CV number, 14-bit address, and 8-bit mode selection in the memconfig address. The 14-bit address can be used to target a locomotive or an accessory decoder. This will all work when talking to the CS's node id.
> Adds POM support for accessory decoders

- cs/commandstation/ProgrammingTrackFrontend.hxx
Some decoders that have a lot of onboard capacitance, and are very close to the program track steady state current limits, can experience an increase in current following an ack. This can result sometimes result in a current fault being detected.
Increasing the number of reset packets when the program track starts provides a bit more time for the onboard capacitance to charge up ahead of the first ack. This provides a bit of extra discharge capacity when the ack comes, preventing the expected uptick in charging current following the ack from triggering a current fault.
> Increase the number of program track startup reset packets

- cs/commandstation/FindProtocolDefs.cxx
- cs/commandstation/FindProtocolDefs.cxxtest
- cs/commandstation/FindProtocolDefs.hxx
- Adds helper function that implements the recommendation for headless throttles for using the find protocol. This differs from query and allocate in the attributes selected in the flag byte.
- Gneeralizes the test framework to work with all three options. Adds a lot more unit tests. Adds tests for retrieving openlcb native locomotives.
> Updates FindProtocolDefs for supporting headless throttles
